#!/bin/bash
sudo rm -rfv /var/lib/apt/lists/*

sudo parrot-upgrade

#sudo apt clean
#sudo apt update --fix-missing
#sudo apt upgrade

#sudo apt-get clean
#sudo apt-get update --fix-missing
#sudo apt-get upgrade
